#!/bin/bash

tab=$1

backgrounds_folder="${2:-$HOME/Pictures/backgrounds}"

chosen_picture=${3:-""}
echo "$chosen_picture" > /tmp/rofi2.log

# if the backgrounds folder is not the default one add $HOME/Pictures/backgrounds to the beginning of it




if [ "$tab" == "1" ]; then
    modi_option="theme-menu"
    echo "theme-menu"
  elif [ "$tab" == "2" ]; then
    modi_option="backgrounds"
    echo "backgrounds"
  elif [ "$tab" == "3" ]; then
    modi_option="style"
    echo "style"
  else
    echo "Invalid tab number. Please specify either 1 or 2."
    exit 1
fi
#

modi="'theme-menu:~/.config/rofi/scripts/rofi-themes,backgrounds:~/.config/rofi/scripts/rofi-backgrounds.sh \"\" $backgrounds_folder $chosen_picture',style:~/.config/rofi/scripts/rofi-style.sh"


echo "$modi" 


~/.config/rofi/launcher.sh -show $modi_option -modi "$modi"
exit 0
