#!/usr/bin/env bash

set -e
set -u
# Print all the files in ~/Pictures/backgrounds
path=~/Pictures/backgrounds
current_background=$(jq -r '.current_background' ~/.config/rofi/scripts/.custom_config.json)
current_background="${current_background%.*}"
counter=1
for file in "$path"/*; do
    name=$(basename "$file")
    name="${name%.*}"
    if [ "$name" == ".current_background.jpg" ]; then
        continue
    fi

    if [ "$name" == "$(basename "$current_background")" ]; then
        echo -n "󰗠  "
    fi
    echo -n "$counter.) "


    echo "$name"

    ((counter++))
done


if [ $# -gt 0 ]; then
    selection="$1"
    selection="${selection#[0-9]*.) }"
    killall -q rofi
else
    echo "No selection provided." >&2
    exit 1
fi


# replace "current_background": "...." in json from ~/.config/rofi/scripts/.custom_config.json with the full path
if [ -f "$path/$selection.jpg" ]; then
    path="$path/$selection.jpg"
elif [ -f "$path/$selection.png" ]; then
    path="$path/$selection.png"
else
    echo "Neither $path.jpg nor $path.png exists." >&2
    exit 1
fi



sed -i "s|\"current_background\": \".*\"|\"current_background\": \"$path\"|" ~/.config/rofi/scripts/.custom_config.json

# cp the selected background to ~/Pictures/backgrounds/current_background.jpg
cp "$path" ~/Pictures/backgrounds/.current_background.jpg

# set the background
killall swaybg || true
swaybg -i ~/Pictures/backgrounds/.current_background.jpg &
eww reload

# restart rofi
~/.config/hypr/scripts/rofi-themes 2

